#include "eventsdata.h"

const LunarEventRule lunarEvents[] = {
    {QString::fromUtf8("युगादि नव वर्ष"), QString::fromUtf8("चन्द्रमान अनुसार नयाँ वर्षको सुरुवात।"), QString::fromUtf8("चैत्र"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("प्रतिपदा"), EventRule::Udaya, false},
    {QString::fromUtf8("चैते दशैँ"), QString::fromUtf8("चैत्र महिनामा मनाइने दशैँ, ठूलो दशैँको सानो रूप।"), QString::fromUtf8("चैत्र"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("अष्टमी"), EventRule::Udaya, false},
    {QString::fromUtf8("रामनवमी"), QString::fromUtf8("भगवान रामको जन्मदिन (मध्याह्न काल)।"), QString::fromUtf8("चैत्र"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("नवमी"), EventRule::Madhyanna, true},
    {QString::fromUtf8("मातातीर्थ औंसी"), QString::fromUtf8("आमाको मुख हेर्ने दिन।"), QString::fromUtf8("वैशाख"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("अमावस्या"), EventRule::Udaya, false},
    {QString::fromUtf8("घोडेजात्रा"), QString::fromUtf8("काठमाडौँमा मनाइने घोडे जात्रा उत्सव।"), QString::fromUtf8("चैत्र"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("अमावस्या"), EventRule::Madhyanna, true},
    {QString::fromUtf8("अक्षय तृतीया"), QString::fromUtf8("जौ सातु खाने दिन, विवाहको लागि शुभ साइत।"), QString::fromUtf8("वैशाख"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("तृतीया"), EventRule::Udaya, false},
    {QString::fromUtf8("बुद्ध जयन्ती / उभौली पर्व"), QString::fromUtf8("भगवान बुद्धको जन्म र किराँत समुदायको उभौली पर्व।"), QString::fromUtf8("वैशाख"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पूर्णिमा"), EventRule::Udaya, true},
    {QString::fromUtf8("सिथि नख:"), QString::fromUtf8("नेवार समुदायले इनार तथा पानीका मुहान सफा गर्ने र कुमार कार्तिकेयको पूजा गर्ने पर्व।"), QString::fromUtf8("ज्येष्ठ"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("षष्ठी"), EventRule::Udaya, false},
    {QString::fromUtf8("निर्जला एकादशी"), QString::fromUtf8("जल समेत नपिई व्रत बस्ने कठोर एकादशी।"), QString::fromUtf8("ज्येष्ठ"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("एकादशी"), EventRule::Udaya, false},
    {QString::fromUtf8("हरिशयनी एकादशी (तुलसी रोपण)"), QString::fromUtf8("चतुर्मास व्रत सुरु, घर-घरमा तुलसी रोप्ने दिन।"), QString::fromUtf8("आषाढ"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("एकादशी"), EventRule::Udaya, false},
    {QString::fromUtf8("गुरु पूर्णिमा"), QString::fromUtf8("गुरु र शिक्षकहरूलाई सम्मान गर्ने दिन।"), QString::fromUtf8("आषाढ"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पूर्णिमा"), EventRule::Udaya, false},
    {QString::fromUtf8("गठाःमुगः चह्रे (घन्टाकर्ण)"), QString::fromUtf8("दुष्ट आत्माहरूलाई भगाउने नेवारी पर्व।"), QString::fromUtf8("श्रावण"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("चतुर्दशी"), EventRule::Udaya, false},
    {QString::fromUtf8("नाग पञ्चमी"), QString::fromUtf8("सर्प देवताको पूजा गर्ने र ढोकामा नाग टाँस्ने दिन।"), QString::fromUtf8("श्रावण"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पञ्चमी"), EventRule::Udaya, false},
    {QString::fromUtf8("जनै पूर्णिमा / रक्षा बन्धन"), QString::fromUtf8("जनै बदल्ने तथा रक्षा बन्धन बाँध्ने, क्वाँटी खाने दिन।"), QString::fromUtf8("श्रावण"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पूर्णिमा"), EventRule::Udaya, true},
    {QString::fromUtf8("कृष्ण जन्माष्टमी"), QString::fromUtf8("भगवान कृष्णको जन्मदिन (निशीथ काल)।"), QString::fromUtf8("भाद्र"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("अष्टमी"), EventRule::Nishitha, true},
    {QString::fromUtf8("गाईजात्रा"), QString::fromUtf8("दिवंगत आत्माको शान्तिको लागि मनाइने उत्सव।"), QString::fromUtf8("भाद्र"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("प्रतिपदा"), EventRule::Udaya, true},
    {QString::fromUtf8("कुशे औंसी (बुवाको मुख हेर्ने)"), QString::fromUtf8("बुवाको सम्मान गर्ने दिन।"), QString::fromUtf8("भाद्र"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("अमावस्या"), EventRule::Udaya, false},
    {QString::fromUtf8("हरितालिका तीज"), QString::fromUtf8("महिलाहरूको महान उत्सव, शिव-पार्वतीको पूजा।"), QString::fromUtf8("भाद्र"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("तृतीया"), EventRule::Udaya, true},
    {QString::fromUtf8("गणेश चतुर्थी"), QString::fromUtf8("भगवान गणेशको जन्मदिन (मध्याह्न काल)।"), QString::fromUtf8("भाद्र"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("चतुर्थी"), EventRule::Madhyanna, false},
    {QString::fromUtf8("ऋषि पञ्चमी"), QString::fromUtf8("महिलाहरूले सप्तऋषिको पूजा गर्ने विशेष दिन।"), QString::fromUtf8("भाद्र"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पञ्चमी"), EventRule::Udaya, true},
    {QString::fromUtf8("इन्द्रजात्रा"), QString::fromUtf8("काठमाडौँको प्रमुख सडक उत्सव, जीवित देवी कुमारीको रथ यात्रा।"), QString::fromUtf8("भाद्र"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("चतुर्दशी"), EventRule::Udaya, true},
    {QString::fromUtf8("सोह्र श्राद्ध आरम्भ"), QString::fromUtf8("पितृ पक्ष (सोह्र श्राद्ध) सुरु हुने दिन।"), QString::fromUtf8("भाद्र"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पूर्णिमा"), EventRule::Udaya, true},
    {QString::fromUtf8("प्रतिपदा श्राद्ध"), QString::fromUtf8("प्रतिपदा तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("प्रतिपदा"), EventRule::Udaya, false},
    {QString::fromUtf8("द्वितीया श्राद्ध"), QString::fromUtf8("द्वितीया तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("द्वितीया"), EventRule::Udaya, false},
    {QString::fromUtf8("तृतीया श्राद्ध"), QString::fromUtf8("तृतीया तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("तृतीया"), EventRule::Udaya, false},
    {QString::fromUtf8("चतुर्थी श्राद्ध"), QString::fromUtf8("चतुर्थी तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("चतुर्थी"), EventRule::Udaya, false},
    {QString::fromUtf8("पञ्चमी श्राद्ध"), QString::fromUtf8("पञ्चमी तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("पञ्चमी"), EventRule::Udaya, false},
    {QString::fromUtf8("षष्ठी श्राद्ध"), QString::fromUtf8("षष्ठी तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("षष्ठी"), EventRule::Udaya, false},
    {QString::fromUtf8("सप्तमी श्राद्ध"), QString::fromUtf8("सप्तमी तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("सप्तमी"), EventRule::Udaya, false},
    {QString::fromUtf8("अष्टमी श्राद्ध"), QString::fromUtf8("अष्टमी तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("अष्टमी"), EventRule::Udaya, false},
    {QString::fromUtf8("नवमी श्राद्ध"), QString::fromUtf8("नवमी तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("नवमी"), EventRule::Udaya, false},
    {QString::fromUtf8("दशमी श्राद्ध"), QString::fromUtf8("दशमी तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("दशमी"), EventRule::Udaya, false},
    {QString::fromUtf8("एकादशी श्राद्ध"), QString::fromUtf8("एकादशी तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("एकादशी"), EventRule::Udaya, false},
    {QString::fromUtf8("द्वादशी श्राद्ध"), QString::fromUtf8("द्वादशी तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("द्वादशी"), EventRule::Udaya, false},
    {QString::fromUtf8("त्रयोदशी श्राद्ध"), QString::fromUtf8("त्रयोदशी तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("त्रयोदशी"), EventRule::Udaya, false},
    {QString::fromUtf8("चतुर्दशी श्राद्ध"), QString::fromUtf8("चतुर्दशी तिथिमा पर्ने पितृको श्राद्ध गर्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("चतुर्दशी"), EventRule::Udaya, false},
    {QString::fromUtf8("औंसी श्राद्ध (पितृ विसर्जन)"), QString::fromUtf8("पितृ पक्ष समाप्त हुने दिन, सबै पितृको सामूहिक श्राद्ध।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("अमावस्या"), EventRule::Udaya, false},
    {QString::fromUtf8("जितिया पर्व"), QString::fromUtf8("तराईका महिलाहरूले सन्तानको दीर्घायुको लागि मनाउने व्रत।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("अष्टमी"), EventRule::Udaya, true},
    {QString::fromUtf8("घटस्थापना"), QString::fromUtf8("दशैँको सुरुवात, जमरा राख्ने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("प्रतिपदा"), EventRule::Udaya, true},
    {QString::fromUtf8("फूलपाती"), QString::fromUtf8("दशैँको सातौँ दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("सप्तमी"), EventRule::Madhyanna, true},
    {QString::fromUtf8("महाअष्टमी"), QString::fromUtf8("दशैँको आठौँ दिन, कालरात्रिको पूजा।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("अष्टमी"), EventRule::Madhyanna, true},
    {QString::fromUtf8("महानवमी"), QString::fromUtf8("दशैँको नवौं दिन, विश्वकर्मा पूजा।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("नवमी"), EventRule::Udaya, true},
    {QString::fromUtf8("विजयादशमी (दशैं)"), QString::fromUtf8("दशैँको मुख्य दिन, टिका र जमरा लगाउने दिन।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("दशमी"), EventRule::Udaya, true},
    {QString::fromUtf8("कोजाग्रत पूर्णिमा"), QString::fromUtf8("दशैँको अन्त्य, धनकी देवी लक्ष्मीको पूजा।"), QString::fromUtf8("आश्विन"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पूर्णिमा"), EventRule::Nishitha, false},
    {QString::fromUtf8("काग तिहार"), QString::fromUtf8("तिहारको पहिलो दिन, कागलाई समर्पित।"), QString::fromUtf8("कार्तिक"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("त्रयोदशी"), EventRule::Udaya, true},
    {QString::fromUtf8("कुकुर तिहार"), QString::fromUtf8("तिहारको दोस्रो दिन, कुकुरलाई समर्पित।"), QString::fromUtf8("कार्तिक"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("चतुर्दशी"), EventRule::Udaya, true},
    {QString::fromUtf8("लक्ष्मी पूजा"), QString::fromUtf8("तिहारको तेस्रो दिन, गाई तिहार र लक्ष्मी पूजा (प्रदोष काल)।"), QString::fromUtf8("कार्तिक"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("अमावस्या"), EventRule::Pradosh, true},
    {QString::fromUtf8("गोवर्धन पूजा / म्ह पूजा"), QString::fromUtf8("तिहारको चौथो दिन, गोवर्धन पर्वत और आत्म-पूजा (म्ह पूजा)।"), QString::fromUtf8("कार्तिक"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("प्रतिपदा"), EventRule::Udaya, true},
    {QString::fromUtf8("भाइटीका"), QString::fromUtf8("तिहारको पाँचौँ दिन, दाजुभाइ र दिदीबहिनीको पर्व।"), QString::fromUtf8("कार्तिक"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("द्वितीया"), EventRule::Madhyanna, true},
    {QString::fromUtf8("छठ पर्व"), QString::fromUtf8("सूर्य देवतालाई समर्पित तराईको महान पर्व (साँझको अर्घ्य)।"), QString::fromUtf8("कार्तिक"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("षष्ठी"), EventRule::Pradosh, true},
    {QString::fromUtf8("हरिबोधिनी एकादशी (तुलसी विवाह)"), QString::fromUtf8("भगवान विष्णुको जागरण, तुलसी विवाह गर्ने दिन।"), QString::fromUtf8("कार्तिक"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("एकादशी"), EventRule::Udaya, false},
    {QString::fromUtf8("बाला चतुर्दशी"), QString::fromUtf8("पशुपतिनाथमा शतबीज छर्ने विशेष दिन।"), QString::fromUtf8("मार्गशीर्ष"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("चतुर्दशी"), EventRule::Udaya, false},
    {QString::fromUtf8("विवाह पञ्चमी"), QString::fromUtf8("जनकपुरमा भगवान राम र सीताको विवाह महोत्सव।"), QString::fromUtf8("मार्गशीर्ष"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पञ्चमी"), EventRule::Udaya, false},
    {QString::fromUtf8("य:मरि पुन्हि / धान्यपुर्णिमा"), QString::fromUtf8("नेवार समुदायको य:मरि खाने र धान्य पूर्णिमाको उत्सव।"), QString::fromUtf8("मार्गशीर्ष"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पूर्णिमा"), EventRule::Udaya, false},
    {QString::fromUtf8("पितृ स्मृती दिवस"), QString::fromUtf8("पितृ को विशेश सम्झना तथा श्रद्दाञ्जलि गर्ने दिन।"), QString::fromUtf8("पौष"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("अष्टमी"), EventRule::Udaya, false},
    {QString::fromUtf8("स्वस्थानी व्रत आरम्भ"), QString::fromUtf8("श्री स्वस्थानी माताको व्रत तथा कथा सुरु हुने दिन।"), QString::fromUtf8("पौष"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पूर्णिमा"), EventRule::Udaya, false},
    {QString::fromUtf8("सोनाम ल्होछार"), QString::fromUtf8("तामाङ समुदायको नयाँ वर्ष।"), QString::fromUtf8("माघ"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("प्रतिपदा"), EventRule::Udaya, true},
    {QString::fromUtf8("सरस्वती पूजा / वसन्तपञ्चमी"), QString::fromUtf8("ज्ञान र शिक्षाको देवी सरस्वतीको पूजा, वसन्त ऋतुको आगमन।"), QString::fromUtf8("माघ"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पञ्चमी"), EventRule::Udaya, true},
    {QString::fromUtf8("ग्याल्पो ल्होछार"), QString::fromUtf8("शेर्पा समुदायको नयाँ वर्ष।"), QString::fromUtf8("फाल्गुन"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("प्रतिपदा"), EventRule::Udaya, true},
    {QString::fromUtf8("महाशिवरात्रि"), QString::fromUtf8("भगवान शिवको महान रात्रि, पशुपतिनाथमा मेला (निशीथ काल)।"), QString::fromUtf8("फाल्गुन"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("चतुर्दशी"), EventRule::Nishitha, true},
    {QString::fromUtf8("होलिका दहन"), QString::fromUtf8("फागु पूर्णिमाको साँझमा होलिका दहन गरिने।"), QString::fromUtf8("फाल्गुन"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पूर्णिमा"), EventRule::Pradosh, false},
    {QString::fromUtf8("होली (पहाड)"), QString::fromUtf8("रङ्गहरूको उत्सव (पहाडी जिल्लाहरूमा)।"), QString::fromUtf8("फाल्गुन"), QString::fromUtf8("शुक्ल पक्ष"), QString::fromUtf8("पूर्णिमा"), EventRule::Pradosh, true},
    {QString::fromUtf8("होली (तराई)"), QString::fromUtf8("रङ्गहरूको उत्सव (तराई जिल्लाहरूमा)।"), QString::fromUtf8("चैत्र"), QString::fromUtf8("कृष्ण पक्ष"), QString::fromUtf8("प्रतिपदा"), EventRule::Pradosh, true},
};
const int numLunarEvents = sizeof(lunarEvents) / sizeof(lunarEvents[0]);

const FixedEventRule gregorianEvents[] = {
    {QString::fromUtf8("अङ्ग्रेजी नयाँ वर्ष"), QString::fromUtf8("ग्रेगोरियन क्यालेन्डरको पहिलो दिन।"), 1, 1, 0, true},
    {QString::fromUtf8("विश्व ब्रेल दिवस"), QString::fromUtf8("ब्रेल लिपिको महत्व झल्काउने दिन।"), 1, 4, 0, false},
    {QString::fromUtf8("अन्तर्राष्ट्रिय शिक्षा दिवस"), QString::fromUtf8("शान्ति र विकासका लागि शिक्षाको भूमिका।"), 1, 24, 0, false},
    {QString::fromUtf8("विश्व क्यान्सर दिवस"), QString::fromUtf8("क्यान्सर विरुद्ध जनचेतना फैलाउने दिन।"), 2, 4, 0, false},
    {QString::fromUtf8("भ्यालेन्टाइन डे"), QString::fromUtf8("प्रेमको उत्सव मनाउने दिन।"), 2, 14, 0, false},
    {QString::fromUtf8("अन्तर्राष्ट्रिय मातृभाषा दिवस"), QString::fromUtf8("सांस्कृतिक विविधता र मातृभाषाको संरक्षण।"), 2, 21, 0, false},
    {QString::fromUtf8("अन्तर्राष्ट्रिय नारी दिवस"), QString::fromUtf8("महिला अधिकार र सशक्तिकरणको लागि।"), 3, 8, 0, true},
    {QString::fromUtf8("विश्व पानी दिवस"), QString::fromUtf8("स्वच्छ पानीको महत्व र संरक्षण।"), 3, 22, 0, false},
    {QString::fromUtf8("विश्व स्वास्थ्य दिवस"), QString::fromUtf8("ग्लोबल स्वास्थ्य जागरूकताका लागि।"), 4, 7, 0, false},
    {QString::fromUtf8("पृथ्वी दिवस"), QString::fromUtf8("पर्यावरण संरक्षणको लागि विश्वव्यापी दिन।"), 4, 22, 0, false},
    {QString::fromUtf8("अन्तर्राष्ट्रिय श्रमिक दिवस / मदजुर दिवस"), QString::fromUtf8("श्रमिकहरूको योगदानको सम्मानमा।"), 5, 1, 0, true},
    {QString::fromUtf8("विश्व प्रेस स्वतन्त्रता दिवस"), QString::fromUtf8("प्रेस स्वतन्त्रता र निर्भिक पत्रकारिताको लागि।"), 5, 3, 0, false},
    {QString::fromUtf8("विश्व रेडक्रस दिवस"), QString::fromUtf8("रेडक्रसको मानवीय सेवाको सम्मानमा।"), 5, 8, 0, false},
    {QString::fromUtf8("विश्व वातावरण दिवस"), QString::fromUtf8("पर्यावरण संरक्षणको जनचेतनाका लागि।"), 6, 5, 0, false},
    {QString::fromUtf8("विश्व शरणार्थी दिवस"), QString::fromUtf8("शरणार्थीहरूको साहस र संघर्षको सम्मानमा।"), 6, 20, 0, false},
    {QString::fromUtf8("अन्तर्राष्ट्रिय योग दिवस"), QString::fromUtf8("योग र स्वस्थ जीवनशैलीको महत्व।"), 6, 21, 0, false},
    {QString::fromUtf8("विश्व जनसंख्या दिवस"), QString::fromUtf8("जनसंख्या सम्बन्धी चुनौतीहरूको बारेमा।"), 7, 11, 0, false},
    {QString::fromUtf8("अन्तर्राष्ट्रिय युवा दिवस"), QString::fromUtf8("युवाहरूको सशक्तिकरण र सहभागिताको लागि।"), 8, 12, 0, false},
    {QString::fromUtf8("अन्तर्राष्ट्रिय साक्षरता दिवस"), QString::fromUtf8("साक्षरताको महत्व झल्काउने दिन।"), 9, 8, 0, false},
    {QString::fromUtf8("अन्तर्राष्ट्रिय लोकतन्त्र दिवस"), QString::fromUtf8("लोकतान्त्रिक मूल्य र मान्यताको प्रवर्द्धन।"), 9, 15, 0, false},
    {QString::fromUtf8("अन्तर्राष्ट्रिय शान्ति दिवस"), QString::fromUtf8("विश्वभर शान्ति र अहिंसाको सन्देश।"), 9, 21, 0, false},
    {QString::fromUtf8("विश्व शिक्षक दिवस"), QString::fromUtf8("शिक्षकहरूको योगदानको कदर गर्ने दिन।"), 10, 5, 0, false},
    {QString::fromUtf8("विश्व खाद्य दिवस"), QString::fromUtf8("खाद्य सुरक्षा र भोकमरी विरुद्धको चेतना।"), 10, 16, 0, false},
    {QString::fromUtf8("संयुक्त राष्ट्र संघ दिवस"), QString::fromUtf8("संयुक्त राष्ट्र संघको स्थापना दिवस।"), 10, 24, 0, false},
    {QString::fromUtf8("विश्व बाल दिवस"), QString::fromUtf8("बाल अधिकार र कल्याणको प्रवर्द्धन।"), 11, 20, 0, false},
    {QString::fromUtf8("विश्व एड्स दिवस"), QString::fromUtf8("एड्स विरुद्ध जनचेतना फैलाउने दिन।"), 12, 1, 0, false},
    {QString::fromUtf8("अन्तर्राष्ट्रिय मानव अधिकार दिवस"), QString::fromUtf8("मानव अधिकारको विश्वव्यापी घोषणापत्र जारी भएको दिन।"), 12, 10, 0, false},
    {QString::fromUtf8("क्रिसमस डे"), QString::fromUtf8("येशु ख्रिष्टको जन्मोत्सव।"), 12, 25, 0, true},
    {QString::fromUtf8("अङ्ग्रेजी नयाँ वर्षको अघिल्लो दिन"), QString::fromUtf8("ग्रेगोरियन वर्षको अन्तिम दिन।"), 12, 31, 0, true},
};
const int numGregorianEvents = sizeof(gregorianEvents) / sizeof(gregorianEvents[0]);

const FixedEventRule bikramEvents[] = {
    {QString::fromUtf8("लोकतन्त्र दिवस"), QString::fromUtf8("लोकतन्त्रको बहाली भएको दिन।"), 1, 11, 0, true},
    {QString::fromUtf8("गणतन्त्र दिवस"), QString::fromUtf8("नेपाल संघीय लोकतान्त्रिक गणतन्त्र घोषणा भएको दिन।"), 2, 15, 0, true},
    {QString::fromUtf8("राष्ट्रिय धान दिवस"), QString::fromUtf8("असार १५, हिलो खेल्ने र दही चिउरा खाने दिन।"), 3, 15, 0, false},
    {QString::fromUtf8("भानु जयन्ती"), QString::fromUtf8("आदिकवि भानुभक्त आचार्यको जन्म जयन्ती।"), 3, 29, 0, false},
    {QString::fromUtf8("संविधान दिवस"), QString::fromUtf8("नयाँ संविधान जारी भएको ऐतिहासिक दिन।"), 6, 3, 0, true},
    {QString::fromUtf8("पृथ्वी जयन्ती / राष्ट्रिय एकता दिवस"), QString::fromUtf8("नेपालको एकीकरण गर्ने राजा पृथ्वीनारायण शाहको जन्मदिन।"), 9, 27, 0, true},
    {QString::fromUtf8("शहीद दिवस"), QString::fromUtf8("वीर शहीदहरूको सम्झना और सम्मानमा।"), 10, 16, 0, true},
    {QString::fromUtf8("प्रजातन्त्र दिवस"), QString::fromUtf8("२००७ सालको क्रान्ति सफल भई प्रजातन्त्र आएको दिन।"), 11, 7, 0, true},
    {QString::fromUtf8("बिस्का: जात्रा"), QString::fromUtf8("भक्तपुरमा नयाँ वर्षको अवसरमा मनाइने ऐतिहासिक जात्रा।"), 1, 1, 0, true},
    {QString::fromUtf8("बैशाख सङ्क्रान्ति"), QString::fromUtf8("नयाँ वर्षको प्रारम्भ, सूर्य मेष राशिमा प्रवेश।"), 1, 1, 0, true},
    {QString::fromUtf8("जेठ सङ्क्रान्ति"), QString::fromUtf8("सूर्य वृष राशिमा प्रवेश।"), 2, 1, 0, false},
    {QString::fromUtf8("असार सङ्क्रान्ति"), QString::fromUtf8("सूर्य मिथुन राशिमा प्रवेश।"), 3, 1, 0, false},
    {QString::fromUtf8("साउने सङ्क्रान्ति"), QString::fromUtf8("सूर्य कर्कट राशिमा प्रवेश।"), 4, 1, 0, false},
    {QString::fromUtf8("भदौ सङ्क्रान्ति"), QString::fromUtf8("सूर्य सिंह राशिमा प्रवेश।"), 5, 1, 0, false},
    {QString::fromUtf8("असोज सङ्क्रान्ति"), QString::fromUtf8("सूर्य कन्या राशिमा प्रवेश।"), 6, 1, 0, false},
    {QString::fromUtf8("कार्तिक सङ्क्रान्ति"), QString::fromUtf8("सूर्य तुला राशिमा प्रवेश।"), 7, 1, 0, false},
    {QString::fromUtf8("मङ्सिर सङ्क्रान्ति"), QString::fromUtf8("सूर्य वृश्चिक राशिमा प्रवेश।"), 8, 1, 0, false},
    {QString::fromUtf8("पुष सङ्क्रान्ति"), QString::fromUtf8("सूर्य धनु राशिमा प्रवेश।"), 9, 1, 0, false},
    {QString::fromUtf8("माघे सङ्क्रान्ति / उत्तरायण"), QString::fromUtf8("मकर संक्रान्ति र उत्तरायणको आरम्भ।"), 10, 1, 0, true},
    {QString::fromUtf8("फागुन सङ्क्रान्ति"), QString::fromUtf8("सूर्य कुम्भ राशिमा प्रवेश।"), 11, 1, 0, false},
    {QString::fromUtf8("चैत सङ्क्रान्ति"), QString::fromUtf8("सूर्य मीन राशिमा प्रवेश।"), 12, 1, 0, false},
};
const int numBikramEvents = sizeof(bikramEvents) / sizeof(bikramEvents[0]);
