name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies for Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          tools: 'tools_cmake'
          archives: 'qttools qtsvg qtdeclarative qtbase icu'

      - name: Build Project with CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make
