name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install aqt
        run: |
          python -m pip install --upgrade pip
          pip install aqtinstall
          pip install --upgrade aqt
          
      - name: Install Qt
        run: |
          aqt install-qt linux desktop 6.5.0 gcc_64 -m qtbase qttools
      - name: Build Project
        run: |
          mkdir build
          cd build
          qmake ../nepdate.pro
          make
