name: Qt CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo add-apt-repository ppa:beineri/opt-qt-6.2.0 -y
        sudo apt-get update
        sudo apt-get update
        sudo apt-get install -y qt6-default qt6-qmake qt6-base-dev qt6-tools-dev 
        sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/qt6 

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run Executables
      run: |
        cd build
        ./nepdate-widget  # Replace with the name of your Qt executable
        ./nepdate-calendar  # Replace with the name of your Qt executable

