name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.2.*'
        host: 'linux'
        target: 'desktop'
        modules: 'qtbase qttools'  # Add any additional modules you need

    - name: Build Project
      run: |
        mkdir build
        cd build
        qmake ../nepdate.pro
        make
