name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Ensure the correct Python version

    - name: Install aqt
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall

    - name: List Qt versions
      run: |
        aqt list-qt linux desktop

    - name: Install Qt
      run: |
        aqt install-qt linux desktop 6.2.4 gcc_64 -m qtbase qttools

    - name: Build Project
      run: |
        mkdir build
        cd build
        qmake ../nepdate.pro
        make
